vim.cmd('autocmd BufWritePost *.ms execute "!croffpdf %"| redraw!')
vim.cmd("autocmd VimLeavePre * :set guicursor=n-c-v-r-i-ci-ve:ver25")

vim.cmd("autocmd VimEnter * hi CurrentWordTwins guibg=#d2d4d9 gui=none")
vim.cmd("let g:vim_current_word#highlight_current_word = 0")
vim.cmd("let g:vim_current_word#highlight_twins = 1")
vim.cmd("let g:vim_current_word#highlight_delay = 0")

vim.api.nvim_create_user_command("PeekOpen", require("peek").open, {})
vim.api.nvim_create_user_command("PeekClose", require("peek").close, {})

-- highlights
-- vim.cmd('autocmd VimEnter * hi CursorLine guibg=#292e42')
vim.cmd('autocmd VimEnter * hi ScrollView               guibg=#414868')
vim.cmd('autocmd VimEnter * hi NotifyBackground         guibg=#d2d4d9')
vim.cmd('autocmd CursorMoved * hi CursorLineNR          guifg=#1E66F5')
vim.cmd('autocmd VimEnter * hi DiffAdd                  guifg=#40A02B guibg=none')
vim.cmd('autocmd VimEnter * hi DiffChange               guifg=#DF8E1D guibg=none')
vim.cmd('autocmd VimEnter * hi DiffDelete               guifg=#D20F39 guibg=none')
vim.cmd('autocmd VimEnter * hi NvimTreeFolderIcon       guifg=#1E66F5')
vim.cmd('autocmd VimEnter * hi VertSplit                guibg=NONE guifg=#414868')
vim.cmd('autocmd BufEnter * hi StatusLine               guibg=#e6e9ef guibg=#d2d4d9')
vim.cmd('autocmd BufEnter * hi StatusLineNC             guibg=#d2d4d9 guifg=#d2d4d9')
vim.cmd('autocmd BufEnter * hi NvimTreeFolderName       guifg=#1E66F5')
vim.cmd('autocmd BufEnter * hi NvimTreeIndentMarker     guifg=#1E66F5')
vim.cmd('autocmd BufEnter * hi NvimTreeVertSplit        guibg=#e6e9ef guifg=#e6e9ef')
vim.cmd('autocmd BufEnter NvimTree hi NvimTreeStatusLine guibg=#e6e9ef guifg=#e6e9ef')
vim.cmd('autocmd BufEnter NvimTree hi NvimTreeStatusLineNC guibg=#e6e9ef')
vim.cmd('autocmd VimEnter * hi TelescopeNormal          guifg=#4C4F69 guibg=#e6e9ef')
vim.cmd('autocmd VimEnter * hi TelescopeBorder          guifg=#e6e9ef guibg=#e6e9ef')
vim.cmd('autocmd VimEnter * hi TelescopePromptNormal    guifg=#4C4F69 guibg=#d2d4d9')
vim.cmd('autocmd VimEnter * hi TelescopePromptTitle     guifg=#e6e9ef guibg=#D20F39')
vim.cmd('autocmd VimEnter * hi TelescopePromptBorder    guifg=#d2d4d9 guibg=#d2d4d9')
vim.cmd('autocmd VimEnter * hi TelescopePromptPrefix    guifg=#D20F39 guibg=#d2d4d9')
vim.cmd('autocmd VimEnter * hi TelescopeResultsBorder   guifg=#e6e9ef guibg=#e6e9ef')
vim.cmd('autocmd VimEnter * hi TelescopeResultsTitle    guifg=#e6e9ef guibg=#DF8E1D')
vim.cmd('autocmd VimEnter * hi TelescopePreviewBorder   guifg=#e6e9ef guibg=#e6e9ef')
vim.cmd('autocmd VimEnter * hi TelescopePreviewTitle    guifg=#e6e9ef guibg=#40A02B')
vim.cmd('autocmd VimEnter * hi TelescopeSelection       guibg=#d2d4d9')

vim.cmd('autocmd BufEnter * hi PmenuSel                 guifg=none guibg=#d2d4d9')
vim.cmd('autocmd BufEnter * hi Pmenu                    guifg=#e6e9ef guibg=#d2d4d9')
vim.cmd('autocmd BufEnter * hi CmpItemKindField         guifg=#e6e9ef guibg=#D20F39')
vim.cmd('autocmd BufEnter * hi CmpItemKindProperty      guifg=#e6e9ef guibg=#D20F39')
vim.cmd('autocmd BufEnter * hi CmpItemKindEvent         guifg=#e6e9ef guibg=#D20F39')
vim.cmd('autocmd BufEnter * hi CmpItemKindText          guifg=#e6e9ef guibg=#40A02B')
vim.cmd('autocmd BufEnter * hi CmpItemKindEnum          guifg=#e6e9ef guibg=#40A02B')
vim.cmd('autocmd BufEnter * hi CmpItemKindKeyword       guifg=#e6e9ef guibg=#40A02B')
vim.cmd('autocmd BufEnter * hi CmpItemKindConstant      guifg=#e6e9ef guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindConstructor   guifg=#e6e9ef guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindReference     guifg=#e6e9ef guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindFunction      guifg=#e6e9ef guibg=#EA76CB')
vim.cmd('autocmd BufEnter * hi CmpItemKindStruct        guifg=#e6e9ef guibg=#EA76CB')
vim.cmd('autocmd BufEnter * hi CmpItemKindClass         guifg=#e6e9ef guibg=#EA76CB')
vim.cmd('autocmd BufEnter * hi CmpItemKindModule        guifg=#e6e9ef guibg=#EA76CB')
vim.cmd('autocmd BufEnter * hi CmpItemKindOperator      guifg=#e6e9ef guibg=#EA76CB')
vim.cmd('autocmd BufEnter * hi CmpItemKindVariable      guifg=#e6e9ef guibg=#ACB0BE')
vim.cmd('autocmd BufEnter * hi CmpItemKindFile          guifg=#e6e9ef guibg=#ACB0BE')
vim.cmd('autocmd BufEnter * hi CmpItemKindUnit          guifg=#e6e9ef guibg=#DF8E1D')
vim.cmd('autocmd BufEnter * hi CmpItemKindSnippet       guifg=#e6e9ef guibg=#DF8E1D')
vim.cmd('autocmd BufEnter * hi CmpItemKindFolder        guifg=#e6e9ef guibg=#DF8E1D')
vim.cmd('autocmd BufEnter * hi CmpItemKindMethod        guifg=#e6e9ef guibg=#1E66F5')
vim.cmd('autocmd BufEnter * hi CmpItemKindValue         guifg=#e6e9ef guibg=#1E66F5')
vim.cmd('autocmd BufEnter * hi CmpItemKindEnumMember    guifg=#e6e9ef guibg=#1E66F5')
vim.cmd('autocmd BufEnter * hi CmpItemKindInterface     guifg=#e6e9ef guibg=#179299')
vim.cmd('autocmd BufEnter * hi CmpItemKindColor         guifg=#e6e9ef guibg=#179299')
vim.cmd('autocmd BufEnter * hi CmpItemKindTypeParameter guifg=#e6e9ef guibg=#179299')

vim.cmd('autocmd BufEnter * hi CmpItemAbbrDeprecated    guifg=#ACB0BE guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemAbbrMatch         guifg=#434549 guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemAbbrMatchFuzzy    guifg=#434549 guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemMenu              guifg=#EA76CB guibg=none')
