#!/bin/sh

# colors for status2d

# dark mode
red="^c#F38BA8^"
redfg="^b#F38BA8^"
blue="^c#89B4FA^"
lightblue="^c#94E2D5^"
pink="^c#F5C2E7^"
lime="^c#73daca^"
orange="^c#f7ceaf^"
green="^c#A6E3A1^"
yellow="^c#F9E2AF^"
gray="^c#CDD6F4^"
# bg="^b#2E2E3E^"
bg=""
