-- vim.cmd('autocmd VimEnter * hi Normal guibg=NONE')

vim.cmd('autocmd BufWritePost *.ms execute "!croffpdf %"| redraw!')
vim.cmd('autocmd VimLeavePre * :set guicursor=n-c-v-r-i-ci-ve:ver25')

-- highlights
-- vim.cmd('autocmd VimEnter * hi CursorLine guibg=#292e42')
vim.cmd('autocmd VimEnter * hi ScrollView guibg=#414868')
-- vim.cmd('autocmd VimEnter * hi LineNr guifg=#414868')
vim.cmd('autocmd CursorMoved * hi CursorLineNR guifg=#1E66F5')
vim.cmd('autocmd VimEnter * hi DiffAdd guifg=#40A02B guibg=none')
vim.cmd('autocmd VimEnter * hi DiffChange guifg=#DF8E1D guibg=none')
vim.cmd('autocmd VimEnter * hi DiffDelete guifg=#D20F39 guibg=none')
vim.cmd('autocmd VimEnter * hi NvimTreeFolderIcon guifg=#1E66F5')
vim.cmd('autocmd VimEnter * hi VertSplit guibg=NONE guifg=#414868')
vim.cmd('autocmd BufEnter * hi StatusLine guibg=#e6e9ef guibg=#d2d4d9')
vim.cmd('autocmd BufEnter * hi StatusLineNC guibg=#d2d4d9 guifg=#d2d4d9')
vim.cmd('autocmd BufEnter * hi NvimTreeFolderName guifg=#1E66F5')
vim.cmd('autocmd BufEnter * hi NvimTreeIndentMarker guifg=#1E66F5')
vim.cmd('autocmd BufEnter * hi NvimTreeVertSplit guibg=#e6e9ef guifg=#e6e9ef')
vim.cmd('autocmd BufEnter * hi NvimTreeStatusLine guibg=#e6e9ef guifg=#e6e9ef')
vim.cmd('autocmd BufEnter * hi NvimTreeStatusLineNC guibg=#e6e9ef')
-- vim.cmd('autocmd VimEnter * hi TelescopeNormal guifg=#d2d4d9 guibg=#e6e9ef')
-- vim.cmd('autocmd VimEnter * hi TelescopeBorder guifg=#e6e9ef guibg=#e6e9ef')
-- vim.cmd('autocmd VimEnter * hi TelescopePromptNormal guifg=#d2d4d9 guibg=#d2d4d9')
-- vim.cmd('autocmd VimEnter * hi TelescopePromptTitle guifg=#e6e9ef guibg=#D20F39')
-- vim.cmd('autocmd VimEnter * hi TelescopePromptBorder guifg=#d2d4d9 guibg=#d2d4d9')
-- vim.cmd('autocmd VimEnter * hi TelescopePromptPrefix guifg=#D20F39 guibg=#d2d4d9')
-- vim.cmd('autocmd VimEnter * hi TelescopeResultsBorder guifg=#e6e9ef guibg=#e6e9ef')
-- vim.cmd('autocmd VimEnter * hi TelescopeResultsTitle guifg=#e6e9ef guibg=#DF8E1D')
-- vim.cmd('autocmd VimEnter * hi TelescopePreviewBorder guifg=#e6e9ef guibg=#e6e9ef')
-- vim.cmd('autocmd VimEnter * hi TelescopePreviewTitle guifg=#e6e9ef guibg=#40A02B')
-- vim.cmd('autocmd VimEnter * hi TelescopeSelection guibg=#d2d4d9')
