#!/bin/sh

# colors for status2d

# light mode
red="^c#D20F39^"
redfg="^b#D20F39^"
blue="^c#1E66F5^"
lightblue="^c#179299^"
pink="^c#EA76CB^"
lime="^c#73daca^"
orange="^c#DF8E1D^"
green="^c#40A02B^"
yellow="^c#dfb71d^"
gray="^c#ACB0BE^"
bg="^b#EAEAF0^"
