vim.cmd('autocmd BufWritePost *.ms execute "!croffpdf %"| redraw!')
vim.cmd('autocmd VimLeavePre * :set guicursor=n-c-v-r-i-ci-ve:ver25')

vim.cmd('autocmd VimEnter * hi CurrentWordTwins guibg=#dddddd gui=none')
vim.cmd('let g:vim_current_word#highlight_current_word = 0')
vim.cmd('let g:vim_current_word#highlight_twins = 1')
vim.cmd('let g:vim_current_word#highlight_delay = 0')

-- highlights
-- vim.cmd('autocmd VimEnter * hi CursorLine guibg=#292e42')
-- vim.cmd('autocmd VimEnter * hi LineNr guifg=#414868')
vim.cmd('autocmd VimEnter * hi ScrollView               guibg=#414868')
vim.cmd('autocmd CursorMoved * hi CursorLineNR          guifg=#82cfff')
vim.cmd('autocmd VimEnter * hi DiffAdd                  guifg=#42be65 guibg=none')
vim.cmd('autocmd VimEnter * hi DiffChange               guifg=#FFAB91 guibg=none')
vim.cmd('autocmd VimEnter * hi DiffDelete               guifg=#ee5396 guibg=none')
vim.cmd('autocmd VimEnter * hi NvimTreeFolderIcon       guifg=#82cfff')
vim.cmd('autocmd VimEnter * hi VertSplit                guibg=NONE guifg=#414868')
vim.cmd('autocmd BufEnter * hi StatusLine               guibg=#fafafa guibg=#ECEFF1')
vim.cmd('autocmd BufEnter * hi StatusLineNC             guibg=#ECEFF1 guifg=#ECEFF1')
vim.cmd('autocmd BufEnter * hi NvimTreeFolderName       guifg=#82cfff')
vim.cmd('autocmd BufEnter * hi NvimTreeIndentMarker     guifg=#82cfff')
vim.cmd('autocmd BufEnter * hi NvimTreeVertSplit        guibg=#fafafa guifg=#fafafa')
vim.cmd('autocmd BufEnter NvimTree hi NvimTreeStatusLine guibg=#fcfcfc guifg=#fcfcfc')
vim.cmd('autocmd BufEnter NvimTree hi NvimTreeStatusLineNC guifg=#fcfcfc guibg=#fcfcfc')
vim.cmd('autocmd VimEnter * hi TelescopeNormal          guifg=#37474F guibg=#fafafa')
vim.cmd('autocmd VimEnter * hi TelescopeBorder          guifg=#fafafa guibg=#fafafa')
vim.cmd('autocmd VimEnter * hi TelescopePromptNormal    guifg=#37474F guibg=#ffffff')
vim.cmd('autocmd VimEnter * hi TelescopePromptTitle     guifg=#fafafa guibg=#ee5396')
vim.cmd('autocmd VimEnter * hi TelescopePromptBorder    guifg=#ffffff guibg=#ffffff')
vim.cmd('autocmd VimEnter * hi TelescopePromptPrefix    guifg=#ee5396 guibg=#ffffff')
vim.cmd('autocmd VimEnter * hi TelescopeResultsBorder   guifg=#fafafa guibg=#fafafa')
vim.cmd('autocmd VimEnter * hi TelescopeResultsTitle    guifg=#fafafa guibg=#FFAB91')
vim.cmd('autocmd VimEnter * hi TelescopePreviewBorder   guifg=#fafafa guibg=#fafafa')
vim.cmd('autocmd VimEnter * hi TelescopePreviewTitle    guifg=#fafafa guibg=#42be65')
vim.cmd('autocmd VimEnter * hi TelescopeSelection       guibg=#ECEFF1')

vim.cmd('autocmd BufEnter * hi PmenuSel                 guifg=none guibg=#2a2b3c')
vim.cmd('autocmd BufEnter * hi Pmenu                    guifg=#9399b2 guibg=#fafafa')
vim.cmd('autocmd BufEnter * hi CmpItemKindField         guifg=#fafafa guibg=#ee5396')
vim.cmd('autocmd BufEnter * hi CmpItemKindProperty      guifg=#fafafa guibg=#ee5396')
vim.cmd('autocmd BufEnter * hi CmpItemKindEvent         guifg=#fafafa guibg=#ee5396')
vim.cmd('autocmd BufEnter * hi CmpItemKindText          guifg=#fafafa guibg=#42be65')
vim.cmd('autocmd BufEnter * hi CmpItemKindEnum          guifg=#fafafa guibg=#42be65')
vim.cmd('autocmd BufEnter * hi CmpItemKindKeyword       guifg=#fafafa guibg=#42be65')
vim.cmd('autocmd BufEnter * hi CmpItemKindConstant      guifg=#fafafa guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindConstructor   guifg=#fafafa guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindReference     guifg=#fafafa guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindFunction      guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindStruct        guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindClass         guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindModule        guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindOperator      guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindVariable      guifg=#fafafa guibg=#525252')
vim.cmd('autocmd BufEnter * hi CmpItemKindFile          guifg=#fafafa guibg=#525252')
vim.cmd('autocmd BufEnter * hi CmpItemKindUnit          guifg=#fafafa guibg=#FFAB91')
vim.cmd('autocmd BufEnter * hi CmpItemKindSnippet       guifg=#fafafa guibg=#FFAB91')
vim.cmd('autocmd BufEnter * hi CmpItemKindFolder        guifg=#fafafa guibg=#FFAB91')
vim.cmd('autocmd BufEnter * hi CmpItemKindMethod        guifg=#fafafa guibg=#82cfff')
vim.cmd('autocmd BufEnter * hi CmpItemKindValue         guifg=#fafafa guibg=#82cfff')
vim.cmd('autocmd BufEnter * hi CmpItemKindEnumMember    guifg=#fafafa guibg=#82cfff')
vim.cmd('autocmd BufEnter * hi CmpItemKindInterface     guifg=#fafafa guibg=#3ddbd9')
vim.cmd('autocmd BufEnter * hi CmpItemKindColor         guifg=#fafafa guibg=#3ddbd9')
vim.cmd('autocmd BufEnter * hi CmpItemKindTypeParameter guifg=#fafafa guibg=#3ddbd9')

vim.cmd('autocmd BufEnter * hi CmpItemAbbrDeprecated    guifg=#525252 guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemAbbrMatch         guifg=#37474F guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemAbbrMatchFuzzy    guifg=#37474F guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemMenu              guifg=#ff7eb6 guibg=none')
