vim.cmd('autocmd BufWritePost *.ms execute "!croffpdf %"| redraw!')
vim.cmd('autocmd VimLeavePre * :set guicursor=n-c-v-r-i-ci-ve:ver25')

vim.cmd('autocmd VimEnter * hi CurrentWordTwins guibg=#202020 gui=none')
vim.cmd('let g:vim_current_word#highlight_current_word = 0')
vim.cmd('let g:vim_current_word#highlight_twins = 1')
vim.cmd('let g:vim_current_word#highlight_delay = 0')

vim.api.nvim_create_user_command('PeekOpen', require('peek').open, {})
vim.api.nvim_create_user_command('PeekClose', require('peek').close, {})

-- highlights
vim.cmd('autocmd BufEnter * hi CursorLine guibg=#191919')
vim.cmd('autocmd BufEnter * hi ScrollView               guibg=#414868')
vim.cmd('autocmd CursorMoved * hi CursorLineNR          guifg=#82cfff')
vim.cmd('autocmd VimEnter * hi DiffAdd                  guifg=#42be65 guibg=none')
vim.cmd('autocmd VimEnter * hi DiffChange               guifg=#FFAB91 guibg=none')
vim.cmd('autocmd VimEnter * hi DiffDelete               guifg=#ee5396 guibg=none')
vim.cmd('autocmd BufEnter * hi GitSignsAdd              guifg=#42be65 guibg=none')
vim.cmd('autocmd BufEnter * hi GitSignsChange           guifg=#FFAB91 guibg=none')
vim.cmd('autocmd BufEnter * hi GitSignsDelete           guifg=#ee5396 guibg=none')
vim.cmd('autocmd BufEnter * hi Search               	guifg=#F9E2AF')
vim.cmd('autocmd VimEnter * hi DashboardIcon            guifg=#ee5396 guibg=none')
vim.cmd('autocmd VimEnter * hi DashboardKey             guifg=#82cfff guibg=none')
vim.cmd('autocmd VimEnter * hi DashboardDesc            guifg=#525252 guibg=none')
vim.cmd('autocmd VimEnter * hi DashboardHeader          guifg=#525252 guibg=none')
vim.cmd('autocmd VimEnter * hi DashboardFooter          guifg=#9399b2 guibg=none')
vim.cmd('autocmd VimEnter * hi NvimTreeFolderIcon       guifg=#82cfff')
vim.cmd('autocmd VimEnter * hi VertSplit                guibg=NONE guifg=#414868')
vim.cmd('autocmd BufEnter * hi StatusLine               guibg=#fafafa guibg=#ECEFF1')
vim.cmd('autocmd BufEnter * hi StatusLineNC             guibg=#ECEFF1 guifg=#ECEFF1')
vim.cmd('autocmd BufEnter * hi NvimTreeFolderName       guifg=#82cfff')
vim.cmd('autocmd BufEnter * hi NvimTreeIndentMarker     guifg=#82cfff')
vim.cmd('autocmd BufEnter * hi NvimTreeVertSplit        guibg=#fafafa guifg=#fafafa')
vim.cmd('autocmd BufEnter NvimTree hi NvimTreeStatusLine guibg=#fcfcfc guifg=#fcfcfc')
vim.cmd('autocmd BufEnter NvimTree hi NvimTreeStatusLineNC guifg=#fcfcfc guibg=#fcfcfc')
vim.cmd('autocmd VimEnter * hi TelescopeNormal          guifg=#37474F guibg=#fafafa')
vim.cmd('autocmd VimEnter * hi TelescopeBorder          guifg=#fafafa guibg=#fafafa')
vim.cmd('autocmd VimEnter * hi TelescopePromptNormal    guifg=#37474F guibg=#ffffff')
vim.cmd('autocmd VimEnter * hi TelescopePromptTitle     guifg=#fafafa guibg=#ee5396')
vim.cmd('autocmd VimEnter * hi TelescopePromptBorder    guifg=#ffffff guibg=#ffffff')
vim.cmd('autocmd VimEnter * hi TelescopePromptPrefix    guifg=#ee5396 guibg=#ffffff')
vim.cmd('autocmd VimEnter * hi TelescopeResultsBorder   guifg=#fafafa guibg=#fafafa')
vim.cmd('autocmd VimEnter * hi TelescopeResultsTitle    guifg=#fafafa guibg=#FFAB91')
vim.cmd('autocmd VimEnter * hi TelescopePreviewBorder   guifg=#fafafa guibg=#fafafa')
vim.cmd('autocmd VimEnter * hi TelescopePreviewTitle    guifg=#fafafa guibg=#42be65')
vim.cmd('autocmd VimEnter * hi TelescopeSelection       guibg=#ECEFF1')

vim.cmd('autocmd BufEnter * hi PmenuSel                 guifg=none guibg=#2a2b3c')
vim.cmd('autocmd BufEnter * hi Pmenu                    guifg=#9399b2 guibg=#fafafa')
vim.cmd('autocmd BufEnter * hi CmpItemKindField         guifg=#fafafa guibg=#ee5396')
vim.cmd('autocmd BufEnter * hi CmpItemKindProperty      guifg=#fafafa guibg=#ee5396')
vim.cmd('autocmd BufEnter * hi CmpItemKindEvent         guifg=#fafafa guibg=#ee5396')
vim.cmd('autocmd BufEnter * hi CmpItemKindText          guifg=#fafafa guibg=#42be65')
vim.cmd('autocmd BufEnter * hi CmpItemKindEnum          guifg=#fafafa guibg=#42be65')
vim.cmd('autocmd BufEnter * hi CmpItemKindKeyword       guifg=#fafafa guibg=#42be65')
vim.cmd('autocmd BufEnter * hi CmpItemKindConstant      guifg=#fafafa guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindConstructor   guifg=#fafafa guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindReference     guifg=#fafafa guibg=#dfb71d')
vim.cmd('autocmd BufEnter * hi CmpItemKindFunction      guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindStruct        guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindClass         guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindModule        guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindOperator      guifg=#fafafa guibg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi CmpItemKindVariable      guifg=#fafafa guibg=#525252')
vim.cmd('autocmd BufEnter * hi CmpItemKindFile          guifg=#fafafa guibg=#525252')
vim.cmd('autocmd BufEnter * hi CmpItemKindUnit          guifg=#fafafa guibg=#FFAB91')
vim.cmd('autocmd BufEnter * hi CmpItemKindSnippet       guifg=#fafafa guibg=#FFAB91')
vim.cmd('autocmd BufEnter * hi CmpItemKindFolder        guifg=#fafafa guibg=#FFAB91')
vim.cmd('autocmd BufEnter * hi CmpItemKindMethod        guifg=#fafafa guibg=#82cfff')
vim.cmd('autocmd BufEnter * hi CmpItemKindValue         guifg=#fafafa guibg=#82cfff')
vim.cmd('autocmd BufEnter * hi CmpItemKindEnumMember    guifg=#fafafa guibg=#82cfff')
vim.cmd('autocmd BufEnter * hi CmpItemKindInterface     guifg=#fafafa guibg=#3ddbd9')
vim.cmd('autocmd BufEnter * hi CmpItemKindColor         guifg=#fafafa guibg=#3ddbd9')
vim.cmd('autocmd BufEnter * hi CmpItemKindTypeParameter guifg=#fafafa guibg=#3ddbd9')

vim.cmd('autocmd BufEnter * hi CmpItemAbbrDeprecated    guifg=#525252 guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemAbbrMatch         guifg=#37474F guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemAbbrMatchFuzzy    guifg=#37474F guibg=none')
vim.cmd('autocmd BufEnter * hi CmpItemMenu              guifg=#ff7eb6 guibg=none')

vim.cmd('autocmd BufEnter * hi BarbecueContextFile          guibg=#161616 guifg=#525252')
vim.cmd('autocmd BufEnter * hi BarbecueContextModule        guibg=#161616 guifg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi BarbecueContextNamespace        guibg=#161616 guifg=#42be65')
vim.cmd('autocmd BufEnter * hi BarbecueContextPackage         guibg=#161616 guifg=#ee5396')
vim.cmd('autocmd BufEnter * hi BarbecueContextClass         guibg=#161616 guifg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi BarbecueContextMethod        guibg=#161616 guifg=#82cfff')
vim.cmd('autocmd BufEnter * hi BarbecureContectProperty      guibg=#161616 guifg=#3ddbd9')
vim.cmd('autocmd BufEnter * hi BarbecueContextField         guibg=#161616 guifg=#ee5396')
vim.cmd('autocmd BufEnter * hi BarbecueContextConstructor   guibg=#161616 guifg=#F9E2AF')
vim.cmd('autocmd BufEnter * hi BarbecueContextEnum          guibg=#161616 guifg=#42be65')
vim.cmd('autocmd BufEnter * hi BarbecueContextInterface     guibg=#161616 guifg=#3ddbd9')
vim.cmd('autocmd BufEnter * hi BarbecueContextFunction      guibg=#161616 guifg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi BarbecueContextVariable      guibg=#161616 guifg=#525252')
vim.cmd('autocmd BufEnter * hi BarbecueContextConstant      guibg=#161616 guifg=#F9E2AF')
vim.cmd('autocmd BufEnter * hi BarbecueContextString      guibg=#161616 guifg=#82cfff')
vim.cmd('autocmd BufEnter * hi BarbecueContextNumber      guibg=#161616 guifg=#82cfff')
vim.cmd('autocmd BufEnter * hi BarbecueContextBoolean      guibg=#161616 guifg=#F9E2AF')
vim.cmd('autocmd BufEnter * hi BarbecueContextArray      guibg=#161616 guifg=#F9E2AF')
vim.cmd('autocmd BufEnter * hi BarbecueContextObject      guibg=#161616 guifg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi BarbecueContextKey			guibg=#161616 guifg=#42be65')
vim.cmd('autocmd BufEnter * hi BarbecueContextNull         guibg=#161616 guifg=#ee5396')
vim.cmd('autocmd BufEnter * hi BarbecueContextEnumMember    guibg=#161616 guifg=#82cfff')
vim.cmd('autocmd BufEnter * hi BarbecueContextText          guibg=#161616 guifg=#42be65')
vim.cmd('autocmd BufEnter * hi BarbecueContextStruct        guibg=#161616 guifg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi BarbecueContextEvent        guibg=#161616 guifg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi BarbecueContextOperator      guibg=#161616 guifg=#ff7eb6')
vim.cmd('autocmd BufEnter * hi BarbecueContextReference     guibg=#161616 guifg=#F9E2AF')
vim.cmd('autocmd BufEnter * hi BarbecueContextTypeParameter guibg=#161616 guifg=#3ddbd9')
