#!/bin/sh

# colors for status2d

# dark mode
red="^b#ee5396^"
redfg="^c#ee5396^"
blue="^b#82cfff^"
lightblue="^b#3ddbd9^"
pink="^b#ff7eb6^"
lime="^b#73daca^"
orange="^b#FFAB91^"
green="^b#42be65^"
yellow="^b#dfb71d^"
gray="^b#37474F^"
bg="^c#ECEFF1^"
